apiVersion: v1
kind: Secret
metadata:
  name: pgpass1
  namespace: jobs
data:
  .pgpass: {{ vault_pgpass | b64encode }}
---
apiVersion: v1
data:
  .dockerconfigjson: your.docker.login.credentials
kind: Secret
metadata:
  name: canister
  namespace: jobs
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: aws
  namespace: jobs
data:
  aws_id: {{ vault_aws.id | b64encode }}
  aws_key: {{ vault_aws.key | b64encode }}