---
dependencies: []

galaxy_info:
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - web
    - system
    - containers
    - docker
    - orchestration
    - compose
    - server
