---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
linux_user: centos

docker_edition: 'ce'
docker_version: '18.06.1.ce-3.el7'
docker_package: "docker-{{ docker_edition }}-{{ docker_version }}"
docker_package_state: present

lvm2_version: '2.02.185-2.el7'
#lvm2_package: "lvm2-{{ lvm2_version }}"
lvm2_package: "lvm2"
lvm2_package_state: present

data_mapper_version: '1.02.158-2.el'
data_mapper_package: "device-mapper-persistent-data"
data_mapper_package_state: present

docker_compose_version: '1.18.0-4.el7'
docker_compose_package: "docker-compose-{{ docker_compose_version }}"
docker_compose_package_state: present

# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true

# Used only for RedHat/CentOS/Fedora.
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_edge: 0
docker_yum_repo_enable_test: 0

# A list of users who will be added to the docker group.
docker_users: ['centos']
