---
- name: Ensure containerd service dir exists.
  file:
    path: /etc/systemd/system/containerd.service.d
    state: directory

- name: Add shim to ensure Docker can start in all environments.
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/containerd.service.d/override.conf
  register: override_template

- name: Setup config for Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  register: override_config

- name: Reload systemd daemon if template is changed.
  systemd:
    daemon_reload: true
  when: override_template is changed

- name: restart docker daemon if config is changed.
  systemd:
    name: docker
    state: restarted
  when: override_config is changed

- name: Extract Docker-compose sources
  unarchive:
    src: ./files/compose-postgres-metabase.tar.gz
    dest: /home/{{ linux_user }}/

- name: Install Docker compose py
  pip:
    name: docker-compose
    version: 1.24.1